pipeline:
  - stage: retrieval
    function: get_top_relevant_documents
    parameters:
      query: "{{query}}"
      top_n: 2
    cot_template: |
      Retrieving the top 2 relevant segments for the query "{query}".

  - stage: qa_over_guide
    function: answer_query_from_guide
    parameters:
      query: "{{query}}"
    cot_template: |
      Generating an answer to "{query}" based on the retrieved guide segments.
    prompt_template: |
      You are an AI assistant tasked with answering user queries using the official documentation provided below.

      ############################
      # USER’S QUERY
      ############################
      {query}

      ############################
      # DOCUMENTATION EXCERPTS
      ############################
      {guide_chunks}

      ############################
      # INSTRUCTIONS
      ############################
      1. **Objective**: Provide a clear and accurate answer to the user’s query based solely on the provided documentation excerpts.

      2. **Answer Requirements**:
         - Begin with a concise, direct answer to the query.
         - Follow with a detailed explanation, referencing specific parts of the documentation where applicable.
         - If the documentation does not contain sufficient information, respond with: "No relevant information found in the guide."

      3. **Formatting Guidelines**:
         - Use clear and simple language.
         - Structure your answer in paragraphs.
         - Highlight key steps, instructions, or configurations mentioned in the documentation.

      4. **Additional Constraints**:
         - Do not introduce external information beyond the provided excerpts.
         - Ensure that the answer is self-contained and comprehensible without requiring additional context.

      ############################
      # FINAL ANSWER
      ############################
      Provide your final, polished answer below.
