# n_papers_protocol.yaml

pipeline:
  - stage: retrieval
    function: run_retrieval
    parameters:
      query: "{{user_query}}"
      top_n: 5
    prompt_template: |
      Retrieve the top {top_n} relevant chunks for the query "{user_query}" from the collection containing multiple documents.

  - stage: reasoning
    function: run_reasoning
    parameters:
      query: "{{user_query}}"
      chunks: "{{retrieval_output}}"
    prompt_template: |
      Initial Answer Generation:
      Query: {user_query}

      Context:
      {context_chunks}

      Please provide a concise initial answer to the query and indicate the source (filename) for each key piece of information.
    cot_questions:
      - "What are the main ideas extracted from the retrieved chunks? Indicate sources."
      - "Are there any contradictions or differing perspectives among the sources? If so, which chunks?"
      - "How can information from different chunks be combined to form a more comprehensive answer? Indicate sources."
      - "Which chunks (sources) appear most reliable, and why? Provide a brief justification referencing chunk IDs."
      - "Is any relevant information missing? Which additional chunks or sources could fill that gap?"
      - "Summarize the final answer by integrating all relevant information and clearly indicating sources."

  - stage: qa_over_pdf
    function: run_qa_over_pdf
    parameters:
      query: "{{user_query}}"
      chunks: "{{retrieval_output}}"
    prompt_template: |
      Based on the following chunks extracted from multiple PDF documents, please answer the query:
      {user_query}

      Context (chunks with sources):
      {context_text}

      Provide your answer, clearly indicating the source (filename) for each piece of information.
